version: '2'
services:
  db:
    restart: always
    build: db/.
    container_name: clicc_db
    volumes_from:
      - data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: clicc
      POSTGRES_PASSWORD: clicc
  data:
    image: clicc_db
    container_name: clicc_data
    volumes:
      - /var/lib/postgresql/
    command: echo 'Data Container for PostGIS'
  dev:
    restart: always
    build: dev/.
    container_name: clicc_dev
    ports:
      - "443:8888"
    environment: 
      PASSWORD: clicc
      USE_HTTPS: 'yes'
    links: 
      - db